Logs started here 2020-05-03T23:59:01.752
First connection start 2020-05-03T23:59:02.007
Lost connect #1 2020-05-03T23:59:27.010
An exception occurred during operation 2020-05-03T23:59:28.265 :  
Failed to connect to 'localhost:8080': Connection refused: connect
An exception occurred during operation 2020-05-03T23:59:39.521 :  
Failed to connect to 'localhost:8080': Connection refused: connect
Connection restored 2020-05-03T23:59:54.848
Lost connect #2 2020-05-04T00:00:54.859
An exception occurred during operation 2020-05-04T00:00:56.112 :  
Failed to connect to 'localhost:8080': Connection refused: connect
An exception occurred during operation 2020-05-04T00:01:07.377 :  
Failed to connect to 'localhost:8080': Connection refused: connect
Connection restored 2020-05-04T00:01:22.455
Lost connect #3 2020-05-04T00:02:37.463
An exception occurred during operation 2020-05-04T00:02:38.727 :  
Failed to connect to 'localhost:8080': Connection refused: connect
